### register request
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email":"useremail@gmail.com",
    "password":"some strong password",
    "name":"user full name"
}

### login request 
POST http://localhost:3000/api/auth/login
Content-Type: application/json
{
    "email":"useremail@gmail.com",
    "password":"some strong password"
}

### authorized routes
GET http://localhost:3000/api/post
Content-Type: application/json
auth-token: auth-token you recieve in header
